# Generated by Django 4.0.1 on 2022-02-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
